### ISSUE TITLE
Bug in UI: Deadlock?

### ISSUE THREAD

**Issue by dominicparga** [sgs-us/microtrafficsim#24]
These steps follows into the problem:
Starting UI, pressing `m`, cancel map-loading (`esc` or clicking `cancel`), pressing `m`
=> deadlock or similar; program does not react and has to be stopped by IDE

my system: MacBook Pro Late 2013 running macOS Sierra 10.12.1

**Comment by dominicparga** [comment]
Line
int action = chooser.showOpenDialog(null);
in SimulationController hangs. Could be a Java Bug (http://stackoverflow.com/questions/18642158/why-does-jfilechooser-showopendialog-hang-on-mac-osx)

**Comment by qzed** [comment]
No deadlock with OpenJDK 1.8.0_112-b15 using Linux (64bit).

**Comment by dominicparga** [comment]
FIXED:
Replace the line `int action = chooser.showOpenDialog(null)` by
`int action = chooser.showDialog(null, "Öffnen");`
The window showing up looks not similar but the choice can be canceled and accepted.

**Comment by dominicparga** [comment]
It showed up that I implemented the interaction with the Swing/AWT Threads wrong due to misunderstanding of their functionality. This causes a deadlock sometimes. This could be fixed by using own (or from OpenJDK) ExecutorServices. Now we use
`int action = chooser.showOpenDialog(null)`
