### ISSUE TITLE
Make logic edges deterministic by deterministic ID-allocation

### ISSUE THREAD

**Issue by dominicparga** [sgs-us/microtrafficsim#26]
The routing has to be deterministic. This can be done by making IDs of nodes and edges deterministic. The node ID is given by OpenStreetMap.

**Comment by qzed** [comment]
The generation of internal IDs is deterministic, i.e. depends on solely OSM IDs. Missing hash-functions have been added with Commit 30a398a2731ed3c78e8dc81f42d246274944f285 .
