### ISSUE TITLE
Inconsistency between tile-based visualization and traffic logic

### ISSUE THREAD

**Issue by dominicparga** [sgs-us/microtrafficsim#4]
If a osm-file contains nodes, which are out of the osm-file's graph bounds, they are considered in the traffic logic, but not shown in the visualization (depending on the zoom level).

**Comment by qzed** [comment]
_TODO_: Recompute the bounds and/or clip the geometry during preprocessing.

**Comment by qzed** [comment]
Added option to choose between clipping geometry to bounds, recomputing the bounds or doing nothing (see `FeatureGenerator.Properties`, used by the `OSMParser` and underlying parser interfaces).
